# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Test

on: pull_request

permissions:
  contents: read

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.0',  '8.1',  '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php-versions }} test

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up dependencies
        run: composer i

      - name: Lint
        run: php -f convert.php tests/test.php tests/test.rst

      - name: Check RST changes
        run: |
          bash -c "[[ ! \"`git status --porcelain `\" ]] || (echo 'Please test and commit the result, see the section \"Show changes on failure\" for details' && exit 1)"

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [test]

    if: always()

    name: test-summary

    steps:
      - name: Summary status
        run: if ${{ needs.test.result != 'success' }}; then exit 1; fi
